// <auto-generated> 콜 헤드 가중치(SmallTichuWeights). CallNetTrainer 가 생성. 손으로 편집 금지. </auto-generated>
namespace Tichu.GameFlow.Agents
{
    public static class SmallTichuWeights
    {
        public const int FeatureCount = 16;
        public const double Bias = -5.7287016992914666;
        public const double Threshold = 0.5;
        public static readonly double[] Weights = new double[] { 1.5566789239161491, -0.16755630004714547, 0.8483345858782155, 0.4418064127478717, -1.6809630293735498, 0.9861964429720654, 0.9193351646855283, 0.36114861686141103, -0.10795029554519453, 1.2255351870193347, 1.0895574054826507, 0.8732006218527053, -1.40083214001125, 0.7655039010966305, 5.828481232435281, 0.9527658038287954 };
    }
}
