using System;
using System.Collections.Generic;
using Tichu.Core;
using Tichu.Core.Game;

namespace Tichu.Core.Tests.Sim
{
    /// <summary>
    /// 헤드리스 시뮬레이터: RandomBot으로 엔진을 한 라운드 / 한 게임 구동한다.
    /// </summary>
    internal static class Simulator
    {
        // ── 라운드 ─────────────────────────────────────────────────────────────────

        /// <summary>
        /// 한 라운드를 처음부터 끝까지 돌린다.
        /// - 모든 Apply가 Ok임을 보장(아니면 예외).
        /// - Phase==Scoring에 도달하면 ScoreCalculator.ScoreRound 호출.
        /// - 최종 상태 + RoundResult + 적용한 액션 목록을 반환.
        /// </summary>
        public static (GameState State, RoundResult Result, IReadOnlyList<GameAction> Log)
            PlayRound(ulong seed)
        {
            var s = GameEngine.NewRound(seed);
            // 게임 셔플과 같은 시드로 인한 상관관계 방지(봇 선택이 딜과 얽히지 않게).
            var rng = new Rng(seed ^ 0xDEADBEEFCAFEBABEUL); // 봇 Rng는 게임 Rng와 분리
            var log = new List<GameAction>();

            RunRound(s, ref rng, log);

            var result = ScoreCalculator.ScoreRound(s);
            return (s, result, log);
        }

        /// <summary>
        /// 기록된 액션 로그를 동일 seed에서 재생하여 최종 해시를 반환한다.
        /// 결정성 검증용.
        /// </summary>
        public static ulong ReplayRound(ulong seed, IReadOnlyList<GameAction> log)
        {
            var s = GameEngine.NewRound(seed);
            foreach (var action in log)
            {
                var r = GameEngine.Apply(s, action);
                if (!r.Ok)
                    throw new InvalidOperationException(
                        $"Replay failed on action {action.Kind}/{action.Seat}: {r.RejectReason}");
            }
            ScoreCalculator.ScoreRound(s);
            return s.ComputeHash();
        }

        // ── 게임 ───────────────────────────────────────────────────────────────────

        /// <summary>
        /// 여러 라운드를 돌려 한 팀이 targetScore 이상에 도달하거나 maxRounds에 도달할 때 종료.
        /// 각 라운드의 점수를 누적한 단일 ScoreBoard가 담긴 최종 상태를 반환.
        /// </summary>
        public static GameState PlayGame(ulong seed, int targetScore = 1000, int maxRounds = 10000)
        {
            var masterRng = new Rng(seed);
            GameState? lastState = null;
            int teamA = 0, teamB = 0;

            for (int round = 0; round < maxRounds; round++)
            {
                ulong roundSeed = masterRng.NextULong();
                var (s, result, _) = PlayRound(roundSeed);

                teamA += result.TeamATotal;
                teamB += result.TeamBTotal;

                // 누적 합계를 마지막 상태에 기록한다.
                s.Scores.TeamA = teamA;
                s.Scores.TeamB = teamB;
                lastState = s;

                if (teamA >= targetScore || teamB >= targetScore)
                    return lastState;
            }

            throw new InvalidOperationException(
                $"Game exceeded {maxRounds} rounds without a winner (A={teamA}, B={teamB})");
        }

        // ── 내부 구동 루프 ─────────────────────────────────────────────────────────

        private static void RunRound(GameState s, ref Rng rng, List<GameAction> log)
        {
            const int MaxSteps = 100_000; // 안전 상한 (무한 루프 방지)
            int steps = 0;

            // 셋업 페이즈 진행 추적 (Setup은 internal이므로 로컬로 인덱스 관리).
            // RoundSetup(다음 차례 좌석)는 internal이라 GameState가 셋업 페이즈의 현재 좌석을 노출하지 않는다.
            // 엔진의 순차 처리 순서(좌석 0→3)를 수동으로 미러링한다.
            int grandTichuNext = 0; // 다음으로 큰 티츄 결정을 내릴 자리
            int exchangeNext   = 0; // 다음으로 교환을 제출할 자리

            while (s.Phase != RoundPhase.Scoring)
            {
                if (++steps > MaxSteps)
                    throw new InvalidOperationException(
                        $"Round exceeded {MaxSteps} steps without reaching Scoring phase. " +
                        $"Phase={s.Phase}, Turn={s.Turn}");

                GameAction action = ChooseAction(s, ref rng, ref grandTichuNext, ref exchangeNext);
                var result = GameEngine.Apply(s, action);
                if (!result.Ok)
                    throw new InvalidOperationException(
                        $"Illegal action generated by bot: {action.Kind}/seat={action.Seat} " +
                        $"in phase {s.Phase}: {result.RejectReason}");

                log.Add(action);
            }
        }

        private static GameAction ChooseAction(
            GameState s,
            ref Rng rng,
            ref int grandTichuNext,
            ref int exchangeNext)
        {
            switch (s.Phase)
            {
                case RoundPhase.GrandTichuDecision:
                {
                    int seat = grandTichuNext++;
                    bool call = rng.NextInt(RandomBot.GrandTichuRateValue) == 0;
                    return call
                        ? GameAction.CallGrandTichu(seat)
                        : GameAction.DeclineGrandTichu(seat);
                }

                case RoundPhase.Exchange:
                {
                    int seat = exchangeNext++;
                    return RandomBot.DecideExchange(s, seat);
                }

                case RoundPhase.Play:
                    return RandomBot.DecidePlay(s, ref rng);

                default:
                    throw new InvalidOperationException($"Unexpected phase in RunRound: {s.Phase}");
            }
        }
    }
}
