using System;
using System.IO;
using System.Text;
using Tichu.Core.Game;
using Tichu.GameFlow;
using Tichu.GameFlow.Agents;

namespace Tichu.Core.Tests.Bench
{
    /// <summary>
    /// B1 오프라인 트레이너. 휴리스틱 self-play 로 (8장 피처, out-first 라벨) 을 만들고,
    /// 손짠 SGD 로 로지스틱 회귀를 학습해 가중치를 방출한다. 순수 C#·파이썬 0.
    /// GenerateData/TrainLogistic 는 결정적. 무거운 학습·방출은 [Explicit].
    /// </summary>
    public static class CallNetTrainer
    {
        /// <summary>rounds 라운드 휴리스틱 self-play. 각 라운드 4좌석의 8장 피처 + FinishOrder==1 라벨.</summary>
        public static (float[][] X, int[] y) GenerateData(int rounds, ulong baseSeed)
        {
            var X = new float[rounds * 4][];
            var y = new int[rounds * 4];
            for (int r = 0; r < rounds; r++)
            {
                ulong seed = baseSeed + (ulong)r;
                var s = GameEngine.NewRound(seed);
                // 8장 손패 스냅샷(플레이 전 — RunRound 가 손패를 비운다).
                var feats = new float[4][];
                for (int seat = 0; seat < 4; seat++)
                    feats[seat] = GrandTichuFeatures.Encode(s.Seats[seat].Hand);
                // 순수 휴리스틱 self-play(콜 헤드 OFF — 라벨은 콜과 무관).
                var agents = new IAgent[4];
                for (int seat = 0; seat < 4; seat++) agents[seat] = new AiAgent(seed, seat);
                var outcome = new GameDriver(agents).RunRound(s);
                for (int seat = 0; seat < 4; seat++)
                {
                    X[r * 4 + seat] = feats[seat];
                    y[r * 4 + seat] = outcome.State.Seats[seat].FinishOrder == 1 ? 1 : 0;
                }
            }
            return (X, y);
        }

        /// <summary>로지스틱 회귀 SGD(이진 크로스엔트로피 + L2). 마지막 10%는 검증셋.</summary>
        public static (double[] w, double b, double logloss, double acc) TrainLogistic(
            float[][] X, int[] y, int epochs, double lr, double l2, ulong seed)
        {
            int n = X.Length, dim = GrandTichuFeatures.FeatureCount;
            int valStart = (int)(n * 0.9);
            var w = new double[dim];
            double b = 0.0;
            var rng = new Tichu.Core.Rng(seed);
            var idx = new int[valStart];
            for (int i = 0; i < valStart; i++) idx[i] = i;

            for (int e = 0; e < epochs; e++)
            {
                // Fisher–Yates 셔플(학습셋만).
                for (int i = valStart - 1; i > 0; i--)
                {
                    int j = rng.NextInt(i + 1);
                    (idx[i], idx[j]) = (idx[j], idx[i]);
                }
                for (int t = 0; t < valStart; t++)
                {
                    int i = idx[t];
                    double z = b;
                    for (int d = 0; d < dim; d++) z += w[d] * X[i][d];
                    double p = 1.0 / (1.0 + Math.Exp(-z));
                    double g = p - y[i]; // dL/dz
                    for (int d = 0; d < dim; d++) w[d] -= lr * (g * X[i][d] + l2 * w[d]);
                    b -= lr * g;
                }
            }

            // 검증 지표.
            double ll = 0; int correct = 0, m = n - valStart;
            for (int i = valStart; i < n; i++)
            {
                double z = b;
                for (int d = 0; d < dim; d++) z += w[d] * X[i][d];
                double p = 1.0 / (1.0 + Math.Exp(-z));
                double pc = Math.Min(Math.Max(p, 1e-12), 1 - 1e-12);
                ll += -(y[i] * Math.Log(pc) + (1 - y[i]) * Math.Log(1 - pc));
                if ((p >= 0.5 ? 1 : 0) == y[i]) correct++;
            }
            return (w, b, ll / m, correct / (double)m);
        }

        /// <summary>가중치를 GrandTichuWeights.g.cs 소스로 직렬화(양 미러에 붙여넣을 원문).</summary>
        public static string EmitWeightsSource(double[] w, double b, double threshold)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> B1 Grand 콜 헤드 가중치. CallNetTrainer 가 생성. 손으로 편집 금지. </auto-generated>");
            sb.AppendLine("namespace Tichu.GameFlow.Agents");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GrandTichuWeights");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const int FeatureCount = {w.Length};");
            sb.AppendLine($"        public const double Bias = {b:R};");
            sb.AppendLine($"        public const double Threshold = {threshold:R};");
            sb.Append("        public static readonly double[] Weights = new double[] { ");
            for (int i = 0; i < w.Length; i++) { sb.Append(w[i].ToString("R")); if (i < w.Length - 1) sb.Append(", "); }
            sb.AppendLine(" };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
