// <auto-generated> B1 Grand 콜 헤드 가중치. CallNetTrainer 가 생성. 손으로 편집 금지. </auto-generated>
namespace Tichu.GameFlow.Agents
{
    public static class GrandTichuWeights
    {
        public const int FeatureCount = 16;
        public const double Bias = -3.3732410107378037;
        public const double Threshold = 0.55;
        public static readonly double[] Weights = new double[] { 0.45697463002287153, -0.2539739535536233, 0.6971287103498606, 0.30161553968296007, -1.4306055985505401, 0.9011264613354273, 0.8613894315933548, 0.20302218560998425, 0.04213356510792961, 0.7105609340776665, 0.48586827330054416, 0.12794842115880162, -0.2182662742894681, 0.6008724632510253, 3.1663729550756368, 0.8812579464643863 };
    }
}
