// <auto-generated> B1 Grand 콜 헤드 가중치. CallNetTrainer 가 생성. 손으로 편집 금지. </auto-generated>
namespace Tichu.GameFlow.Agents
{
    public static class GrandTichuWeights
    {
        public const int FeatureCount = 16;
        public const double Bias = 0.0;
        public const double Threshold = 0.5;
        public static readonly double[] Weights = new double[16]; // 플레이스홀더(전부 0)
    }
}
