// <auto-generated> D4 Fork A 가치망 가중치(ValueNetWeights). CallNetTrainer 가 생성. 손으로 편집 금지. </auto-generated>
namespace Tichu.GameFlow.Agents
{
    public static class ValueNetWeights
    {
        public const int FeatureCount = 42;
        public const int Hidden = 32;
        public const double Scale = 100.0;
        public const double B2 = 0.0;
        public static readonly double[] W1 = new double[42 * 32]; // 플레이스홀더(전부 0)
        public static readonly double[] B1 = new double[32];
        public static readonly double[] W2 = new double[32];
    }
}
